export const CATEGORY_PARAM:{[key:string]:any} = {
  'chart': {
    path:'chart/linechart-config',
    param:{}
  },
  'choose':{
    path:'example/node-set',
    param:{
      id:'www',
      name:'itachi'
    }
  },
  'timer':{
    path:'triggers/timer-component',
    param: {
      id:'hh',
      name:'弟弟'
    }
  },
  'trigger_mqtt':{
    path:'triggers/mqtt-component',
    param:{}
  },
  'serial':{
    path:'triggers/serial-component',
    param:{}
  },
  'function':{
    path:'logic/function-component',
    param:{}
  },
  'runExec':{
    path:'data/runexecut-component',
    param:{}
  },
  'tensorFlow':{
    path:'data/tensorflow-component',
    param:{}
  },
  'serial_write':{
    path:'data/serialwrite-component',
    param:{}
  },
  'aws_lambda':{
    path:'data/awslambda-component',
    param:{}
  },
  'modbus_read':{
    path:'data/modbusread-component',
    param:{}
  },
  'output_mqtt':{
    path:'output/mqtt-component',
    param:{}
  },
  'http':{
    path:'output/http-component',
    param:{}
  },
  'debug':{
    path:'output/debug-component',
    param:{}
  }
}