export const CATEGORY_PARAM:{[key:string]:any} = {
  'chart': {
    path:'chart/linechart-config',
    param:{}
  },
  'choose':{
    path:'example/nodeSet',
    param:{
      id:'www',
      name:'itachi'
    }
  },
  'timer':{
    path:'triggers/timerComponent',
    param: {
      id:'hh',
      name:'弟弟'
    }
  },
  'trigger_mqtt':{
    path:'triggers/mqttComponent',
    param:{}
  },
  'serial':{
    path:'triggers/serialComponent',
    param:{}
  },
  'function':{
    path:'logic/functionComponent',
    param:{}
  },
  'runExec':{
    path:'data/runExecutComponent',
    param:{}
  },
  'tensorFlow':{
    path:'data/tensorFlowComponent',
    param:{}
  },
  'serial_write':{
    path:'data/serialWriteComponent',
    param:{}
  },
  'aws_lambda':{
    path:'data/awsLambdaComponent',
    param:{}
  },
  'modbus_read':{
    path:'data/modbusReadComponent',
    param:{}
  },
  'output_mqtt':{
    path:'output/mqttComponent',
    param:{}
  },
  'http':{
    path:'output/httpComponent',
    param:{}
  },
  'debug':{
    path:'output/debugComponent',
    param:{}
  }
}